language: php
php:
  - '7.1'
services:
  - mysql
addons:
  firefox: latest
env:
  - MOZ_HEADLESS=1
  - SELENIUM_FIREFOX_DRIVER=/home/travis/build/geckodriver
  - ZSAMPLE_TEST_URL=http://localhost
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS zsample;'
  - sudo apt-get update > /dev/null
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
install:
  - sudo apt-get install apache2
  - sudo make install
  - make init root_name=root root_pass=
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz
before_script:
  - sudo cp -R /home/travis/build/lotcz/zSample /var/www/
  - sudo cp -R /home/travis/build/lotcz/zEngine /var/www/
  - sudo service apache2 start
script:
  - make test
after_failure:
  - cat zEngine.log
  - cat zSample.log
