language: php
php:
  - '7.1'
services:
  - mysql
addons:
  firefox: latest
env:
  - MOZ_HEADLESS=1
    SELENIUM_FIREFOX_DRIVER=/home/travis/build/lotcz/zSample/geckodriver
    ZSAMPLE_TEST_URL=http://localhost
    ZSAMPLE_ADMIN_LOGIN=travis_admin
    ZSAMPLE_ADMIN_PASS=travis_admin_pass123
    ZSAMPLE_CUSTOMER_EMAIL=travis_customer
    ZSAMPLE_CUSTOMER_PASS=travis_customer_pass123
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS zsample;'
  - sudo apt-get update > /dev/null
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux32.tar.gz && tar -xzf geckodriver-v0.21.0-linux32.tar.gz && sudo chmod a+rwx geckodriver
install:
  - sudo apt-get install apache2
  - sudo make install
  - make init
before_script:
  - sudo service apache2 start
script:
  - make test
after_failure:
  - cat zEngine.log
  - cat zSample.log
