language: php
php:
  - '7.1'
services:
  - mysql
addons:
  firefox: latest
env:
  - MOZ_HEADLESS=1
    SELENIUM_FIREFOX_DRIVER=/home/travis/build/lotcz/zSample/geckodriver
    ZSAMPLE_TEST_URL=http://localhost
    ZSAMPLE_VISITOR_EMAIL=travis_visitor@test.com
    ZSAMPLE_VISITOR_PASS=travis_customer_pass123
    ZSAMPLE_ADMIN_EMAIL=travis_admin@test.com
    ZSAMPLE_ADMIN_PASS=travis_admin_pass123
before_install:
  - sudo apt-get update > /dev/null
  - wget https://goo.gl/FCSwwD -O selenium-server.jar
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux32.tar.gz
  - tar -xzf geckodriver-v0.21.0-linux32.tar.gz
install:
  - sudo apt-get install apache2
  - sudo service apache2 start
  - mysql -e 'CREATE DATABASE IF NOT EXISTS zsample;'
  - sudo make install_files
  - make install_db prepare_test
before_script:
  - make adduser visitor_email=$ZSAMPLE_VISITOR_EMAIL visitor_password=$ZSAMPLE_VISITOR_PASS admin_email=$ZSAMPLE_ADMIN_EMAIL admin_password=$ZSAMPLE_ADMIN_PASS
  - nohup java -jar -Dwebdriver.gecko.driver=$SELENIUM_FIREFOX_DRIVER selenium-server.jar &
script:
  - make test
  - cat /home/travis/nohup.out
after_failure:
  - cat zEngine.log
  - cat zSample.log
