language: php
php:
  - '7.1'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS zsample;'
  - sudo apt-get update > /dev/null
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
install:
  - sudo apt-get install apache2
  - sudo make install
  - make init root_name=root root_pass=
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz
  - export SELENIUM_FIREFOX_DRIVER=/home/travis/build/geckodriver
before_script:
  - sudo cp -R /home/travis/build/lotcz/zSample /var/www/
  - sudo cp -R /home/travis/build/lotcz/zEngine /var/www/
  - sudo service apache2 start
  - sudo echo "127.0.0.1 zsample.loc" >> /etc/hosts
script:
  - make test
after_failure:
  - cat zEngine.log
  - cat zSample.log
